{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "github-actions-cache-server.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "github-actions-cache-server.labels" . | nindent 4 }}
spec:
  {{- if ne (.Values.podDisruptionBudget.minAvailable | toString) "" }}
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  {{- else }}
  maxUnavailable: {{ .Values.podDisruptionBudget.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "github-actions-cache-server.selectorLabels" . | nindent 6 }}
{{- end }}
